baseURL = ""
languageCode = "en-us"
title = "Go See Talents"
baseurl = "/"
themesDir = "../.."
[permalinks]
  post = "/:year/:month/:day/:slug/"   

[[menu.main]]
    name = "Hive"
    url = "/hive/"
[[menu.main]]
    name = "AboutUs"
    url = "/aboutus/"